--[[
 ██████╗██████╗ ███████╗██████╗ ██╗████████╗███████╗
██╔════╝██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝██╔════╝
██║     ██████╔╝█████╗  ██║  ██║██║   ██║   ███████╗
██║     ██╔══██╗██╔══╝  ██║  ██║██║   ██║   ╚════██║
╚██████╗██║  ██║███████╗██████╔╝██║   ██║   ███████║
 ╚═════╝╚═╝  ╚═╝╚══════╝╚═════╝ ╚═╝   ╚═╝   ╚══════╝
                                                    

 All original credit for the Part names goes to Siya (siyamesik#9732)

 ███████╗██╗██╗   ██╗ █████╗      ██╗███████╗██╗██╗   ██╗ █████╗ ███╗   ███╗███████╗███████╗██╗██╗  ██╗ ██╗ ██╗  █████╗ ███████╗██████╗ ██████╗ ██╗ 
██╔════╝██║╚██╗ ██╔╝██╔══██╗    ██╔╝██╔════╝██║╚██╗ ██╔╝██╔══██╗████╗ ████║██╔════╝██╔════╝██║██║ ██╔╝████████╗██╔══██╗╚════██║╚════██╗╚════██╗╚██╗
███████╗██║ ╚████╔╝ ███████║    ██║ ███████╗██║ ╚████╔╝ ███████║██╔████╔██║█████╗  ███████╗██║█████╔╝ ╚██╔═██╔╝╚██████║    ██╔╝ █████╔╝ █████╔╝ ██║
╚════██║██║  ╚██╔╝  ██╔══██║    ██║ ╚════██║██║  ╚██╔╝  ██╔══██║██║╚██╔╝██║██╔══╝  ╚════██║██║██╔═██╗ ████████╗ ╚═══██║   ██╔╝  ╚═══██╗██╔═══╝  ██║
███████║██║   ██║   ██║  ██║    ╚██╗███████║██║   ██║   ██║  ██║██║ ╚═╝ ██║███████╗███████║██║██║  ██╗╚██╔═██╔╝ █████╔╝   ██║  ██████╔╝███████╗██╔╝
╚══════╝╚═╝   ╚═╝   ╚═╝  ╚═╝     ╚═╝╚══════╝╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚══════╝╚═╝╚═╝  ╚═╝ ╚═╝ ╚═╝  ╚════╝    ╚═╝  ╚═════╝ ╚══════╝╚═╝ 
                                                                                                                                                   
 Credit for *painfully* turning all the if statements to tables goes to Korabi (Korabi#6344)
                                                                                                           
 _|    _|                                _|        _|    _|  _|      _|_|_|  _|_|_|    _|  _|    _|  _|    
 _|  _|      _|_|    _|  _|_|    _|_|_|  _|_|_|        _|_|_|_|_|  _|              _|  _|  _|    _|  _|    
 _|_|      _|    _|  _|_|      _|    _|  _|    _|  _|    _|  _|    _|_|_|      _|_|    _|_|_|_|  _|_|_|_|  
 _|  _|    _|    _|  _|        _|    _|  _|    _|  _|  _|_|_|_|_|  _|    _|        _|      _|        _|    
 _|    _|    _|_|    _|          _|_|_|  _|_|_|    _|    _|  _|      _|_|    _|_|_|        _|        _|    
                                                                                                           
                                                                                                                                                

Yes I did the stupid ascii art thing everyone does, FUCKING CRY ABOUT IT.                                                             
]]--
local colors = {}
colors.house_walls = {
	"SmoothBlockModel103",
	"SmoothBlockModel105",
	"SmoothBlockModel106",
	"SmoothBlockModel108",
	"SmoothBlockModel11",
	"SmoothBlockModel113",
	"SmoothBlockModel114",
	"SmoothBlockModel115",
	"SmoothBlockModel116",
	"SmoothBlockModel118",
	"SmoothBlockModel122",
	"SmoothBlockModel126",
	"SmoothBlockModel129",
	"SmoothBlockModel13",
	"SmoothBlockModel130",
	"SmoothBlockModel131",
	"SmoothBlockModel132",
	"SmoothBlockModel134",
	"SmoothBlockModel135",
	"SmoothBlockModel14",
	"SmoothBlockModel140",
	"SmoothBlockModel142",
	"SmoothBlockModel147",
	"SmoothBlockModel15",
	"SmoothBlockModel154",
	"SmoothBlockModel155",
	"SmoothBlockModel164",
	"SmoothBlockModel166",
	"SmoothBlockModel173",
	"SmoothBlockModel176",
	"SmoothBlockModel179",
	"SmoothBlockModel185",
	"SmoothBlockModel186",
	"SmoothBlockModel190",
	"SmoothBlockModel191",
	"SmoothBlockModel196",
	"SmoothBlockModel197",
	"SmoothBlockModel198",
	"SmoothBlockModel20",
	"SmoothBlockModel201",
	"SmoothBlockModel203",
	"SmoothBlockModel205",
	"SmoothBlockModel207",
	"SmoothBlockModel208",
	"SmoothBlockModel209",
	"SmoothBlockModel210",
	"SmoothBlockModel211",
	"SmoothBlockModel213",
	"SmoothBlockModel218",
	"SmoothBlockModel22",
	"SmoothBlockModel223",
	"SmoothBlockModel224",
	"SmoothBlockModel226",
	"SmoothBlockModel26",
	"SmoothBlockModel29",
	"SmoothBlockModel30",
	"SmoothBlockModel31",
	"SmoothBlockModel36",
	"SmoothBlockModel37",
	"SmoothBlockModel38",
	"SmoothBlockModel39",
	"SmoothBlockModel41",
	"SmoothBlockModel48",
	"SmoothBlockModel49",
	"SmoothBlockModel51",
	"SmoothBlockModel56",
	"SmoothBlockModel67",
	"SmoothBlockModel68",
	"SmoothBlockModel69",
	"SmoothBlockModel70",
	"SmoothBlockModel72",
	"SmoothBlockModel75",
	"SmoothBlockModel8",
	"SmoothBlockModel81",
	"SmoothBlockModel85",
	"SmoothBlockModel93",
	"SmoothBlockModel98",
}
colors.house_roof = {
	"SmoothBlockModel100",
	"SmoothBlockModel102",
	"SmoothBlockModel104",
	"SmoothBlockModel107",
	"SmoothBlockModel109",
	"SmoothBlockModel110",
	"SmoothBlockModel111",
	"SmoothBlockModel119",
	"SmoothBlockModel12",
	"SmoothBlockModel120",
	"SmoothBlockModel123",
	"SmoothBlockModel124",
	"SmoothBlockModel125",
	"SmoothBlockModel127",
	"SmoothBlockModel128",
	"SmoothBlockModel133",
	"SmoothBlockModel136",
	"SmoothBlockModel137",
	"SmoothBlockModel138",
	"SmoothBlockModel139",
	"SmoothBlockModel141",
	"SmoothBlockModel143",
	"SmoothBlockModel149",
	"SmoothBlockModel151",
	"SmoothBlockModel152",
	"SmoothBlockModel153",
	"SmoothBlockModel156",
	"SmoothBlockModel157",
	"SmoothBlockModel158",
	"SmoothBlockModel16",
	"SmoothBlockModel163",
	"SmoothBlockModel167",
	"SmoothBlockModel168",
	"SmoothBlockModel169",
	"SmoothBlockModel17",
	"SmoothBlockModel170",
	"SmoothBlockModel172",
	"SmoothBlockModel177",
	"SmoothBlockModel18",
	"SmoothBlockModel180",
	"SmoothBlockModel184",
	"SmoothBlockModel187",
	"SmoothBlockModel188",
	"SmoothBlockModel189",
	"SmoothBlockModel19",
	"SmoothBlockModel193",
	"SmoothBlockModel2",
	"SmoothBlockModel200,",
	"SmoothBlockModel202",
	"SmoothBlockModel21",
	"SmoothBlockModel214",
	"SmoothBlockModel215",
	"SmoothBlockModel216",
	"SmoothBlockModel219",
	"SmoothBlockModel220",
	"SmoothBlockModel221",
	"SmoothBlockModel222",
	"SmoothBlockModel225",
	"SmoothBlockModel227",
	"SmoothBlockModel229",
	"SmoothBlockModel23",
	"SmoothBlockModel230",
	"SmoothBlockModel231",
	"SmoothBlockModel25",
	"SmoothBlockModel28",
	"SmoothBlockModel32",
	"SmoothBlockModel33",
	"SmoothBlockModel34",
	"SmoothBlockModel42",
	"SmoothBlockModel44",
	"SmoothBlockModel47",
	"SmoothBlockModel54",
	"SmoothBlockModel55",
	"SmoothBlockModel58",
	"SmoothBlockModel59",
	"SmoothBlockModel6",
	"SmoothBlockModel61",
	"SmoothBlockModel62",
	"SmoothBlockModel63",
	"SmoothBlockModel74",
	"SmoothBlockModel76",
	"SmoothBlockModel77",
	"SmoothBlockModel78",
	"SmoothBlockModel79",
	"SmoothBlockModel80",
	"SmoothBlockModel84",
	"SmoothBlockModel86",
	"SmoothBlockModel87",
	"SmoothBlockModel88",
	"SmoothBlockModel90",
	"SmoothBlockModel91",
	"SmoothBlockModel92",
	"SmoothBlockModel94",
	"SmoothBlockModel95",
	"SmoothBlockModel96",
}
colors.house_window_door_outlines = {
	"SmoothBlockModel10",
	"SmoothBlockModel101",
	"SmoothBlockModel117",
	"SmoothBlockModel121",
	"SmoothBlockModel144",
	"SmoothBlockModel145",
	"SmoothBlockModel146",
	"SmoothBlockModel148",
	"SmoothBlockModel150",
	"SmoothBlockModel159",
	"SmoothBlockModel161",
	"SmoothBlockModel171",
	"SmoothBlockModel174",
	"SmoothBlockModel175",
	"SmoothBlockModel181",
	"SmoothBlockModel182",
	"SmoothBlockModel183",
	"SmoothBlockModel192",
	"SmoothBlockModel194",
	"SmoothBlockModel195",
	"SmoothBlockModel199",
	"SmoothBlockModel204",
	"SmoothBlockModel206",
	"SmoothBlockModel212",
	"SmoothBlockModel217",
	"SmoothBlockModel228",
	"SmoothBlockModel24",
	"SmoothBlockModel27",
	"SmoothBlockModel35",
	"SmoothBlockModel4",
	"SmoothBlockModel43",
	"SmoothBlockModel45",
	"SmoothBlockModel46",
	"SmoothBlockModel50",
	"SmoothBlockModel53",
	"SmoothBlockModel57",
	"SmoothBlockModel60",
	"SmoothBlockModel64",
	"SmoothBlockModel65",
	"SmoothBlockModel66",
	"SmoothBlockModel7",
	"SmoothBlockModel71",
	"SmoothBlockModel73",
	"SmoothBlockModel82",
	"SmoothBlockModel83",
	"SmoothBlockModel89",
	"SmoothBlockModel99",
}
colors.house_stairs = {
	"SmoothBlockModel1",
	"SmoothBlockModel3",
	"SmoothBlockModel5",
	"SmoothBlockModel9",
}
colors.building_bricks_blue = {
	"Part11",
	"Part18",
	"Part25",
	"Part3",
	"Part43",
}
colors.building_bricks_yellow = {
	"Part12",
	"Part15",
	"Part24",
	"Part44",
	"Part6",
}
colors.green = {
	"Part17",
	"Part26",
	"Part38",
	"Part9",
	"Part5",
}
colors.building_bricks_medium_grey = {
	"Part30",
	"Part32",
	"Part33",
	"Part34",
	"Part35",
	"Part36",
	"Part39",
	"Part40",
	"Part41",
	"Part42",
	"Part46",
	"Part47",
	"Part48",
	"Part49",
	"Part50",
	"Part51",
	"Part52",
	"Part53",
	"Part54",
	"Part56",
	"Part57",
	"Part58",
	"Part59",
	"Part60",
	"Part61",
}
colors.building_bricks_red = {
	"Part1",
	"Part10,",
	"Part16",
	"Part22",
	"Part37",
}
colors.building_bricks_teal = {
	"Part20",
	"Part28",
	"Part4",
	"Part45",
	"Part8",
}
colors.house_chimney_top = { "SmoothBlockModel160", "SmoothBlockModel162", "SmoothBlockModel165", "SmoothBlockModel178" }
colors.building_bricks_black = { "Part14", "Part19", "Part2", "Part27" }
colors.building_bricks_white = { "Part13", "Part21", "Part23", "Part7" }
colors.building_bricks_dark_grey = { "Part29", "Part31", "Part55" }
colors.house_roof_stuff = { "SmoothBlockModel52", "SmoothBlockModel97" }
colors.house_floor = { "SmoothBlockModel112" }
colors.housebase = { "SmoothBlockModel40" }
return colors
